name: Build Project

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Скачиваем и распаковываем SFML
    - name: Download SFML
      run: |
        Invoke-WebRequest -Uri "https://www.sfml-dev.org/files/SFML-2.6.0-windows-vc17-64-bit.zip" -OutFile "sfml.zip"
        Expand-Archive -Path "sfml.zip" -DestinationPath "."
        echo "SFML_PATH=$pwd\SFML-2.6.0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # Устанавливаем зависимости (если нужно)
    - name: Install dependencies
      run: |
        choco install cmake -y
        
    # Сборка проекта
    - name: Build
      run: |
        cmake -B build -S . -DSFML_DIR="$env:SFML_PATH/lib/cmake/SFML"
        cmake --build build --config Release
