name: Build Project

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # Шаг 1: Скачивание кода
    - name: Checkout code
      uses: actions/checkout@v4
      
    # Шаг 2: Установка Visual Studio компонентов
    - name: Install Visual Studio Components
      run: |
        choco install visualstudio2022-workload-vctools -y
        
    # Шаг 3: Настройка окружения
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    # Шаг 4: Сборка проекта
    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --config Release
