name: Build Project

on: [push] # Запускать при каждом push

jobs:
  build:
    runs-on: windows-latest # Используем Windows-агент
    
    steps:
    # Шаг 1: Загрузка кода
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Шаг 2: Установка MSVC (ваш код)
    - name: Setup MSVC
      uses: ms-vssetup/actions/v1@v1
      with:
        installPath: 'C:\Program Files\Microsoft Visual Studio\2022\Community'
        components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64
    
    # Шаг 3: Настройка окружения компилятора
    - name: Configure Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64 # или x86/arm64
    
    # Шаг 4: Ваши команды сборки
    - name: Build project
      run: |
        cmake -B build -S .
        cmake --build build --config Release
